Puzzle4UbyNAM/Puzzle4UbyNAM.Web/Controllers/ProductBrandController.cs
using Microsoft.AspNetCore.Mvc;
using Puzzle4UbyNAM.Models.DTOs.VM;
using Puzzle4UbyNAM.Models.Interfaces;

namespace Puzzle4UbyNAM.Web.Controllers
{
    [Route("[Controller]")]
    public class ProductBrandController : Controller
    {
        private readonly IProductBrandService service;

        public ProductBrandController(IProductBrandService service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = service.GetAllProductBrand();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var dto = new ProductBrandVM();
            return View(dto);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult New(ProductBrandVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(dto);
            }

            service.AddProductBrand(dto);

            return View("Index", service.GetAllProductBrand());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var dto = service.GetProductBrand(id);
            return View(dto);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, ProductBrandVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(dto);
            }

            service.UpdateProductBrand(id, dto);

            return View("Index", service.GetAllProductBrand());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            service.DeleteProductBrand(id);
            return Json(new { success = true, message = "Delete success" });
        }
    }
}

Puzzle4UbyNAM/Puzzle4UbyNAM.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Puzzle4UbyNAM.Models.DTOs.VM;
using Puzzle4UbyNAM.Models.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Puzzle4UbyNAM.Web.Controllers
{
    [Route("[Controller]")]
    public class ProductController : Controller
    {
        private readonly IProductService service;

        public ProductController(IProductService service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = service.GetAllProducts();
            return View(list);
        }

        [HttpGet]
        [Route("Chart")]
        public IActionResult Chart()
        {
            var list = service.GetAllProducts();
            return View(list);
        }

        [HttpGet]
        [Route("Details/{id}")]
        public IActionResult Details(int id)
        {
            var dto = service.GetProduct(id);
            dto.ProductTypes = service.GetProductTypes();
            dto.ProductBrands = service.GetProductBrands();
            return View(dto);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var dto = new ProductVM();
            dto.ProductTypes = service.GetProductTypes();
            dto.ProductBrands = service.GetProductBrands();
            return View(dto);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult New(ProductVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                dto.ProductTypes = service.GetProductTypes();
                dto.ProductBrands = service.GetProductBrands();
                return View(dto);
            }

            service.AddProduct(dto);

            return View("Index", service.GetAllProducts());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var dto = service.GetProduct(id);
            dto.ProductTypes = service.GetProductTypes();
            dto.ProductBrands = service.GetProductBrands();
            return View(dto);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, ProductVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                dto.ProductTypes = service.GetProductTypes();
                dto.ProductBrands = service.GetProductBrands();
                return View(dto);
            }

            service.UpdateProduct(id, dto);

            return View("Index", service.GetAllProducts());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            service.DeleteProduct(id);
            return Json(new { success = true, message = "Delete success" });
        }
    }
}

Puzzle4UbyNAM/Puzzle4UbyNAM.Web/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Puzzle4UbyNAM.Models.DTOs.VM;
using Puzzle4UbyNAM.Models.Interfaces;

namespace Puzzle4UbyNAM.Web.Controllers
{
    [Route("[Controller]")]
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeService service;

        public ProductTypeController(IProductTypeService service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = service.GetAllProductType();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var dto = new ProductTypeVM();
            return View(dto);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult New(ProductTypeVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(dto);
            }

            service.AddProductType(dto);

            return View("Index", service.GetAllProductType());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var dto = service.GetProductType(id);
            return View(dto);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, ProductTypeVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(dto);
            }

            service.UpdateProductType(id, dto);

            return View("Index", service.GetAllProductType());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            service.DeleteProductType(id);
            return Json(new { success = true, message = "Delete success" });
        }
    }
}

Puzzle4UbyNAM/Puzzle4UbyNAM.Web/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@{ 
    var shoppingList = HttpContextAccessor.HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);
    var shoppingCount = shoppingList == null ? 0 : shoppingList.Count;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Puzzle 4U - by NAM (Web)</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/js/site.js"></script>

    <script src="~/js/productType.js"></script>
    <script src="~/js/productBrand.js"></script>
    <script src="~/js/product.js"></script>

</head>
<body>
    <header>
        <div style="background-color: #003976">
        <p style="text-align:center">
            <span style="position:static"> <img src="~/img/Banner2.png" width="1300" /></span>
        </p>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color: #003976">
            <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Puzzle4UbyNAM.Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                @if (User.Identity.IsAuthenticated)
                {
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.Identity.Name == "admin@puzzle4u.ro" )
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ProductType" asp-action="Index">Product Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ProductBrand" asp-action="Index">Product Brand</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Chart"><span class="fas fa-shopping-cart"></span> &nbsp; (@shoppingCount)</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                    </li>

                </ul>
                }
                else
                {
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                </li>
            </ul>
                }
            </div>
        </div> 
        
        </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: #003976">
        <div class="container" style="color: white">
            Puzzle 4U - by NAM (Web) - &copy; Oct 2021
            Logged as @User.Identity.Name
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>